-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contacts" add column "con_id" integer
--  not null unique default '0';
